# Generated by Django 4.2.7 on 2025-03-09 11:53

import data_import.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to=data_import.models.get_file_path, verbose_name='Archivo')),
                ('columns', models.JSONField(blank=True, default=dict, verbose_name='Columnas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Archivo de datos',
                'verbose_name_plural': 'Archivos de datos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('selected_columns', models.JSONField(verbose_name='Columnas seleccionadas')),
                ('chart_type', models.CharField(max_length=50, verbose_name='Tipo de gráfico')),
                ('chart_config', models.JSONField(default=dict, verbose_name='Configuración del gráfico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='data_import.datafile', verbose_name='Archivo de datos')),
            ],
            options={
                'verbose_name': 'Análisis de datos',
                'verbose_name_plural': 'Análisis de datos',
                'ordering': ['-created_at'],
            },
        ),
    ]
