# Generated by Django 4.2.7 on 2025-03-09 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='monthly', max_length=20, verbose_name='Frecuencia')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='1-7, donde 1 es lunes (solo para frecuencia semanal o quincenal)', null=True, verbose_name='Día de la semana')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1-31 (solo para frecuencia mensual)', null=True, verbose_name='Día del mes')),
                ('time', models.TimeField(verbose_name='Hora de envío')),
                ('recipients', models.TextField(help_text='Correos electrónicos separados por comas', verbose_name='Destinatarios')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('message', models.TextField(help_text='Mensaje personalizado para el correo', verbose_name='Mensaje')),
                ('include_data', models.BooleanField(default=True, help_text='Adjuntar datos en el formato seleccionado', verbose_name='Incluir datos')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('png', 'Imagen PNG')], default='pdf', max_length=10, verbose_name='Formato')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Último envío')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='data_import.dataanalysis', verbose_name='Análisis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Informe programado',
                'verbose_name_plural': 'Informes programados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('failed', 'Fallido')], max_length=10, verbose_name='Estado')),
                ('recipients', models.TextField(verbose_name='Destinatarios')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data_visualization.scheduledreport', verbose_name='Informe programado')),
            ],
            options={
                'verbose_name': 'Registro de envío',
                'verbose_name_plural': 'Registros de envío',
                'ordering': ['-sent_at'],
            },
        ),
    ]
